export const media = {
  logo: "/brand/RCC_Horizontal-4C.png",
  nvMag: "/brand/BestDaycare26Teal.webp",
  infant: "/photos/infant.jpg",
  toddler: "/photos/toddler.jpg",
  twos: "/photos/twos.jpg",
  preschool: "/photos/preschool.jpg",
  enrollment: "/photos/enrollment.jpg",
  tuition: "/photos/tuition.jpg",
  sampleLessonPlan: "/photos/sample-lesson-plan.png",
  atmosphere: {
    documentationStudio: "/atmosphere/documentation-studio.png",
    blocksMaterials: "/atmosphere/blocks-materials.png",
    freedomParkDusk: "/atmosphere/freedom-park-dusk.png",
  },
  hero: {
    documentation: "/atmosphere/documentation-studio.png",
    viewbook: "/photos/enrollment.jpg",
    blocks: "/atmosphere/blocks-materials.png",
  },
  rosslyn: "/atmosphere/freedom-park-dusk.png",
  people: {
    dawn: "/photos/people/dawn.png",
    antonella: "/photos/people/antonella.png",
    curtis: "/photos/people/curtis.png",
    camielle: "/photos/people/camielle.png",
    dani: "/photos/people/dani.png",
    danielle: "/photos/people/danielle.png",
    emma: "/photos/people/emma.png",
    inaya: "/photos/people/inaya.png",
    jade: "/photos/people/jade.png",
    may: "/photos/people/may.png",
    mira: "/photos/people/mira.png",
    rashamier: "/photos/people/rashamier.png",
    zander: "/photos/people/zander.png",
    reyna: "/photos/people/reyna.png",
    sophia: "/photos/people/sophia.png",
    tram: "/photos/people/tram.png",
    alanJefferis: "/photos/people/alan-jefferis.png",
    priyalBhatt: "/photos/people/priyal-bhatt.png",
  },
  guides: {
    dawn: "/photos/people/dawn.png",
    antonella: "/photos/people/antonella.png",
    curtis: "/photos/people/curtis.png",
  },
} as const;
